export const yemekler = [
  {
    name: 'kuzutandir',
    yemek: 'Kuzu Tandır',
    malzemeler: [
      '1 kg kuzu eti',
      '2 adet soğan',
      '4 diş sarımsak',
      '2 adet havuç',
      '3-4 dal taze kekik',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
    ],
    yapılış: [
      'Kuzu etini parçalara ayırın.',
      'Soğanları ve sarımsakları doğrayın, havuçları halkalar halinde kesin.',
      'Tüm malzemeleri fırın kabına koyun.',
      'Zeytinyağını ekleyip karıştırın ve baharatları ekleyin.',
      'Önceden ısıtılmış 180 derece fırında 2-3 saat pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2020/12/tatli-patatesli-kuzu.jpg',
  },
  {
    name: 'biberdolmasi',
    yemek: 'Biber Dolması',
    malzemeler: [
      '4 adet dolmalık biber',
      '200 gr kıyma',
      '1 su bardağı pirinç',
      '1 adet soğan',
      '2 adet domates',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '1 su bardağı su',
    ],
    yapılış: [
      'Biberlerin üst kısmını kesin ve içini temizleyin.',
      'Soğanı kavurun, kıymayı ekleyin ve pembeleşinceye kadar kavurun.',
      'Pirinç ve baharatları ekleyin, birkaç dakika daha kavurun.',
      'Karışımı biberlerin içine doldurun.',
      'Biberlerin üzerine dilimlenmiş domates koyun, suyu ekleyin.',
      'Kapağını kapatıp orta ateşte pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mnresize/1250/833/uploads/2015/01/biber-dolmasi-yemekcom.jpg',
  },
  {
    name: 'tavuksote',
    yemek: 'Tavuk Sote',
    malzemeler: [
      '500 gr tavuk göğsü',
      '2 adet biber',
      '1 adet soğan',
      '3 diş sarımsak',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
    ],
    yapılış: [
      'Tavuk göğsünü küp küp doğrayın.',
      'Soğanı ve biberleri doğrayın.',
      'Zeytinyağını tavada ısıtın, soğanları ekleyin.',
      'Soğanlar pembeleşince tavukları ekleyin ve soteleyin.',
      'Biberleri ve baharatları ekleyin, pişene kadar sotelemeye devam edin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2015/08/tavuk-sote-yemekcom.jpg',
  },
  {
    name: 'patatesyemegi',
    yemek: 'Patates Yemeği',
    malzemeler: [
      '4 adet patates',
      '1 adet soğan',
      '2 adet domates',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '1 su bardağı su',
    ],
    yapılış: [
      'Patatesleri soyup küp küp doğrayın.',
      'Soğanı doğrayın ve zeytinyağında kavurun.',
      'Patatesleri ekleyip birkaç dakika soteleyin.',
      'Domatesleri doğrayın, tuz ve baharatları ekleyin.',
      'Su ekleyip kısık ateşte pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2016/04/eli-patates-yemegi-one-cikan-yeni.jpg',
  },
  {
    name: 'kiymali-sebze-yemegi',
    yemek: 'Kıymalı Sebze Yemeği',
    malzemeler: [
      '300 gr kıyma',
      '1 adet patates',
      '1 adet havuç',
      '1 adet kabak',
      '1 adet soğan',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '1 su bardağı su',
    ],
    yapılış: [
      'Soğanı kavurun, kıymayı ekleyin ve pişirin.',
      'Sebzeleri doğrayın ve tavaya ekleyin.',
      'Baharatları ekleyin ve birkaç dakika soteleyin.',
      'Su ekleyip kısık ateşte pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2020/03/firinda-kiymali-sebze-yemegi-yemekcom.jpg',
  },
  {
    name: 'zeytinyagli-enginar',
    yemek: 'Zeytinyağlı Enginar',
    malzemeler: [
      '4 adet enginar',
      '1 adet soğan',
      '1 adet havuç',
      'Tuz',
      'Limon suyu',
      'Zeytinyağı',
    ],
    yapılış: [
      'Enginarları temizleyin ve limonlu suya koyun.',
      'Soğanı ve havucu doğrayın, zeytinyağında kavurun.',
      'Enginarları ekleyin ve tuz ile baharatları ekleyin.',
      'Üzerini kapatıp kısık ateşte pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2015/03/zeytinyagli-enginar-yemekcom.jpg',
  },
  {
    name: 'besamelsoslukarnabahar',
    yemek: 'Beşamel Soslu Karnabahar',
    malzemeler: [
      '1 adet karnabahar',
      '2 yemek kaşığı un',
      '2 yemek kaşığı tereyağı',
      '2 su bardağı süt',
      'Tuz',
      'Karabiber',
      'Kaşar peyniri',
    ],
    yapılış: [
      'Karnabaharı haşlayın.',
      'Tereyağını eritip unu ekleyin, sütü yavaşça ilave edin.',
      'Tuz ve baharatları ekleyip karıştırın.',
      'Haşlanmış karnabaharları sosla kaplayın ve kaşar peyniri serpin.',
      'Fırında üzeri kızarana kadar pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2020/05/besamel-soslu-karnabahar-editorr.jpg',
  },
  {
    name: 'etlinohutyemegi',
    yemek: 'Etli Nohut Yemeği',
    malzemeler: [
      '300 gr et',
      '1 su bardağı nohut',
      '1 adet soğan',
      '2 adet domates',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '2 su bardağı su',
    ],
    yapılış: [
      'Nohutları bir gece önceden ıslatın.',
      'Soğanı kavurun, eti ekleyin ve pişirin.',
      'Nohutları ve doğranmış domatesleri ekleyin.',
      'Su ve baharatları ekleyip kısık ateşte pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2018/05/etli-nohut-tarifi-one-cikan.jpg',
  },
  {
    name: 'lahanalikiymaliyemek',
    yemek: 'Lahanalı Kıymalı Yemek',
    malzemeler: [
      '1 adet lahana',
      '300 gr kıyma',
      '1 adet soğan',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '1 su bardağı su',
    ],
    yapılış: [
      'Lahanayı haşlayın ve yapraklarını ayırın.',
      'Soğanı kavurun, kıymayı ekleyin.',
      'Lahananın yapraklarını doldurun, tencereye dizin.',
      'Su ve baharatları ekleyip pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2015/02/yesil-mercimek-yemekcom.jpg',
  },
  {
    name: 'kiymalipirasayemegi',
    yemek: 'Kıymalı Pırasa Yemeği',
    malzemeler: [
      '4 dal pırasa',
      '300 gr kıyma',
      '1 adet soğan',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '1 su bardağı su',
    ],
    yapılış: [
      'Pırasaları doğrayın.',
      'Soğanı kavurun, kıymayı ekleyin.',
      'Pırasaları ekleyip soteleyin, su ve baharatları ekleyin.',
      'Kısık ateşte pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2024/01/kiymali-pirasa-yemegi-yemekcom.jpg',
  },
];

export const corbalar = [
  {
    name: 'mercimekcorbasi',
    corba: 'Mercimek Çorbası',
    malzemeler: [
      '1 su bardağı kırmızı mercimek',
      '1 adet soğan',
      '1 adet havuç',
      '2 diş sarımsak',
      '1 adet domates',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '4 su bardağı su',
    ],
    yapılış: [
      'Soğanı ve sarımsağı doğrayın, zeytinyağında kavurun.',
      'Havuç ve domatesi ekleyip soteleyin.',
      'Mercimekleri ve suyu ekleyin, tuz ve baharatları ekleyin.',
      'Kaynadıktan sonra kısık ateşte pişirin.',
      'Blender ile pürüzsüz hale getirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2014/06/mercimek-corbasi-yemekcom.jpg',
  },
  {
    name: 'tarhanacorbasi',
    corba: 'Tarhana Çorbası',
    malzemeler: [
      '1 su bardağı tarhana',
      '1 adet soğan',
      '1 adet domates',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '6 su bardağı su',
    ],
    yapılış: [
      'Soğanı kavurun, doğranmış domatesleri ekleyin.',
      'Tarhanayı ekleyin, karıştırın ve suyu ilave edin.',
      'Tuz ve baharatları ekleyip kaynatın.',
      'Kısık ateşte pişirin, karıştırarak kıvamını ayarlayın.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2019/05/tarhana-corbasi-yemekcom.jpg',
  },
  {
    name: 'sebzecorbasi',
    corba: 'Sebze Çorbası',
    malzemeler: [
      '1 adet patates',
      '1 adet havuç',
      '1 adet kabak',
      '1 adet soğan',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '4 su bardağı su',
    ],
    yapılış: [
      'Sebzeleri doğrayın.',
      'Soğanı zeytinyağında kavurun, ardından sebzeleri ekleyin.',
      'Su ve baharatları ekleyip kaynatın.',
      'Sebzeler yumuşayana kadar pişirin ve blendardan geçirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2014/08/terbiyeli-sebze-corbasi.jpg',
  },
  {
    name: 'tavukcorbasi',
    corba: 'Tavuk Suyu Çorbası',
    malzemeler: [
      '1 adet tavuk butu',
      '1 adet havuç',
      '1 adet soğan',
      'Tuz',
      'Karabiber',
      '4 su bardağı su',
      'Yarım su bardağı erişte (isteğe bağlı)',
    ],
    yapılış: [
      'Tavuk butunu ve doğranmış sebzeleri su ile haşlayın.',
      'Tavuk piştikten sonra etleri çıkarın ve didikleyin.',
      'Süzülen suya erişte ekleyin, kaynatın.',
      'Tuz ve baharatları ekleyip tavukları geri koyun, karıştırın.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2014/11/terbiyeli-tavuk-corbasi-yemekcom.jpg',
  },
  {
    name: 'domatescorbasi',
    corba: 'Domates Çorbası',
    malzemeler: [
      '4 adet domates',
      '1 adet soğan',
      '2 diş sarımsak',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '4 su bardağı su',
    ],
    yapılış: [
      'Domatesleri rendeleyin.',
      'Soğan ve sarımsağı kavurun, rendelenmiş domatesi ekleyin.',
      'Su ve baharatları ekleyip kaynatın.',
      'Kıvam alana kadar pişirin ve blendardan geçirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2017/09/feslegenli-domates-corbasi-tarifi.jpg',
  },
  {
    name: 'yaylacorbasi',
    corba: 'Yayla Çorbası',
    malzemeler: [
      '1 su bardağı yoğurt',
      '1 su bardağı pirinç',
      '1 adet yumurta',
      'Tuz',
      'Nane',
      'Zeytinyağı',
      '6 su bardağı su',
    ],
    yapılış: [
      'Pirinçleri haşlayın.',
      'Yoğurdu ve yumurtayı çırpın, suyu ekleyin.',
      'Haşlanmış pirinci ekleyip kaynatın.',
      'Baharatları ekleyip karıştırın, nane ile servis edin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2019/09/kolay-yayla-corbasi-yemekcom.jpg',
  },
  {
    name: 'kiscorbasi',
    corba: 'Kış Çorbası',
    malzemeler: [
      '2 adet havuç',
      '1 adet patates',
      '1 adet karnabahar',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '4 su bardağı su',
    ],
    yapılış: [
      'Sebzeleri doğrayın.',
      'Zeytinyağında sebzeleri kavurun.',
      'Su ve baharatları ekleyin, kaynatın.',
      'Sebzeler yumuşayana kadar pişirin ve blendardan geçirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2022/11/kis-corbasi-yemekcom.jpg',
  },
  {
    name: 'iskembecorbası',
    corba: 'İşkembe Çorbası',
    malzemeler: [
      '500 gr işkembe',
      '1 adet limon',
      'Tuz',
      'Karabiber',
      '2 diş sarımsak',
      '1 su bardağı sirke',
    ],
    yapılış: [
      'İşkembe iyice haşlanır.',
      'Doğranıp, su ile kaynatılır.',
      'Tuz ve baharatları ekleyin.',
      'Servis ederken limon suyu ve sarımsak ile karıştırın.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2023/03/tavuklu-yalanci-iskembe-corbasi-yemekcom.jpg',
  },
  {
    name: 'taratorcorbasi',
    corba: 'Tarator Çorbası',
    malzemeler: [
      '1 su bardağı yoğurt',
      '1/2 su bardağı su',
      '1 adet salatalık',
      '1 diş sarımsak',
      'Tuz',
      'Nane',
      'Zeytinyağı',
    ],
    yapılış: [
      'Yoğurdu ve suyu bir kapta çırpın.',
      'Sarımsak ve doğranmış salatalığı ekleyin.',
      'Tuz ve baharatları ekleyin, zeytinyağı ile süsleyin.',
    ],
    image:
      'https://yemektarifi.yemeksiparisi.com.tr/wp-content/uploads/2023/09/1802-yaz-aylarina-ozel-tarator-corbasi-tarifi.jpg',
  },
  {
    name: 'sehriyecorbasi',
    corba: 'Şehriye Çorbası',
    malzemeler: [
      '1 su bardağı şehriye',
      '1 adet havuç',
      '1 adet soğan',
      'Tuz',
      'Karabiber',
      'Zeytinyağı',
      '6 su bardağı su',
    ],
    yapılış: [
      'Soğanı kavurun, rendelenmiş havucu ekleyin.',
      'Şehriyeleri ekleyip biraz kavurun.',
      'Su ve baharatları ekleyip kaynatın, pişirin.',
    ],
    image:
      'https://cdn.yemek.com/mncrop/620/388/uploads/2021/10/tavuklu-sehriye-corbasi-yemekcom.jpg',
  },
];
